"""empty message

Revision ID: d6334e5a2c66
Revises: 40a87e65abe1
Create Date: 2024-08-19 05:52:50.638837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6334e5a2c66'
down_revision = '40a87e65abe1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=255), nullable=True))

    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.drop_column('image')

    with op.batch_alter_table('Post', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
